---
# tasks file for pyenv

- name: Check if ~/.pyenv exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.pyenv"
  register: dir_stat_result


- name: Installing pyenv
  block:

    - name: Installing dependencies for desired OS
      ansible.builtin.package:
        name: "{{ os_packages[ansible_facts['os_family']] }}"
        state: present
      become: true
      become_user: root

    - name: Running installation script
      ansible.builtin.shell:
        cmd: curl https://pyenv.run | bash

  when: not dir_stat_result.stat.exists


- name: Adding Pyenv setup to .bashrc or .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('\\..*$', '') }}rc"
    block: "{{ pyenv_path_lines }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    marker_begin: Pyenv set up
    marker_end: Pyenv set up end