---
# handlers file for oh-my-zsh

- name: Clonning plugins
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ ohmyzsh_plugin_dir }}/{{ item.repo }}"
  loop: "{{ plugins_repos }}"

- name: Plugins into .zshrc
  ansible.builtin.lineinfile:
    path: "{{ zshrc_file }}"
    regex: '^plugins=\(git\)'
    line: "{{ plugins_replacement }}"
