---
# handlers file for oh-my-zsh

- name: Cleaning install script
  ansible.builtin.file:
    path: "/tmp/{{ ohmyzsh_script }}"
    state: absent


- name: Plugins into .zshrc
  ansible.builtin.lineinfile:
    path: "{{ zshrc_file }}"
    regex: '^plugins=\(git\)'
    line: "{{ plugins_replacement }}"
