---

- name: Crontab Set-Up
  become: true
  become_user: root
  block:
    - name: Installing cronie
      ansible.builtin.dnf:
        name: cronie
        state: present

    - name: Enable and started - crond
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: crond

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ activitywatch_dest_dir }}"
    state: directory
    mode: '0755'

- name: Unzipping ActivityWatch
  ansible.builtin.unarchive:
    src: "{{ activitywatch_dowload_url }}"
    dest: "{{ activitywatch_dest_dir }}"
    remote_src: true
    group: "{{ username }}"
    owner: "{{ groupname }}"

- name: Making ActivityWatch to run at boot (crontab)
  ansible.builtin.cron:
    name: ActivityWatch
    special_time: reboot
    job: "{{ activitywatch_bin }}"
