---
# tasks file for oh-my-zsh

- name: Creatting plugins entry for .zshrc
  set_fact:
    plugins_replacement: "plugins=(git {{ plugins_repos | map(attribute='repo') | join(' ') }})"

- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: latest
  become: true
  become_user: root

- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh_install.sh
    #checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  notify: 
    - Clonning plugins
    - Plugins into .zshrc
